# Generated by Django 4.2.18 on 2025-02-08 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasks',
            table='tasks',
        ),
    ]
