# Generated by Django 4.2.18 on 2025-02-08 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='projects',
            table='projects',
        ),
    ]
